from __future__ import annotations

import asyncio
from types import SimpleNamespace
from typing import Any

import pytest

import fastmcp.cli.cli as fastmcp_cli
import securemcp.cli as securemcp_cli
from fastmcp.cli.install.stdio import stdio_command as fastmcp_stdio_command


class TestSecureMCPCLI:
    def test_app_uses_securemcp_branding(self):
        assert "securemcp" in securemcp_cli.app.name
        assert "SecureMCP" in securemcp_cli.app.help
        assert securemcp_cli.dev_app.help == "Development tools for SecureMCP servers"

    def test_importing_securemcp_cli_does_not_mutate_fastmcp_help(self):
        assert fastmcp_cli.app.help == (
            "FastMCP - The fast, Pythonic way to build MCP servers and clients."
        )
        assert fastmcp_cli.dev_app.help == "Development tools for MCP servers"
        assert fastmcp_cli.project_app.help == "Manage FastMCP projects"

    def test_version_command_reports_securemcp_labels(self, capsys):
        securemcp_cli.version(copy=False)
        output = capsys.readouterr().out

        assert "SecureMCP version:" in output
        assert "Install distribution:" in output

    async def test_fastmcp_example_still_inspects_via_fastmcp_cli(self, capsys):
        command, bound, _ = fastmcp_cli.app.parse_args(["inspect", "examples/echo.py"])

        await command(**bound.arguments)

        output = capsys.readouterr().out
        assert "Echo Server" in output

    async def test_securemcp_example_inspects_via_securemcp_cli(self, capsys):
        command, bound, _ = securemcp_cli.app.parse_args(
            ["inspect", "examples/securemcp/quickstart.py"]
        )

        await command(**bound.arguments)

        output = capsys.readouterr().out
        assert "securemcp-demo" in output

    async def test_fastmcp_install_stdio_stays_fastmcp(self, capsys):
        await fastmcp_stdio_command("examples/securemcp/quickstart.py")

        output = capsys.readouterr().out.strip()
        assert " fastmcp run " in f" {output} "
        assert " securemcp run " not in f" {output} "

    async def test_securemcp_install_stdio_uses_securemcp(self, capsys):
        command, bound, _ = securemcp_cli.app.parse_args(
            ["install", "stdio", "examples/securemcp/quickstart.py"]
        )

        await command(**bound.arguments)

        output = capsys.readouterr().out.strip()
        assert " securemcp run " in f" {output} "
        assert " fastmcp run " not in f" {output} "

    async def test_securemcp_generate_cli_embeds_securemcp_transport(self, tmp_path):
        output = tmp_path / "secure_cli.py"
        command, bound, _ = securemcp_cli.app.parse_args(
            [
                "generate-cli",
                "examples/securemcp/quickstart.py",
                str(output),
                "--no-skill",
                "-f",
            ]
        )

        await command(**bound.arguments)

        content = output.read_text()
        assert "Generated by: securemcp generate-cli" in content
        assert "command='securemcp'" in content

    def test_rewrite_secure_cli_tokens_preserves_fastmcp_dependency_flags(self):
        command = ["uv", "run", "--with", "fastmcp", "fastmcp", "run", "server.py"]

        rewritten = securemcp_cli._rewrite_secure_cli_tokens(command)

        assert rewritten == [
            "uv",
            "run",
            "--with",
            "fastmcp",
            "securemcp",
            "run",
            "server.py",
        ]

    def test_rewrite_secure_cli_tokens_rewrites_module_entrypoint(self):
        command = ["python", "-m", "fastmcp.cli", "run", "server.py"]

        rewritten = securemcp_cli._rewrite_secure_cli_tokens(command)

        assert rewritten == ["python", "-m", "securemcp", "run", "server.py"]

    async def test_securemcp_run_reload_uses_securemcp_command(self, monkeypatch):
        captured: dict[str, list[str]] = {}

        async def fake_run_with_reload(command: list[str], *args, **kwargs) -> None:
            captured["command"] = command

        async def fake_load_server():
            return object()

        config = SimpleNamespace(
            deployment=SimpleNamespace(
                transport="stdio",
                host="127.0.0.1",
                port=8000,
                path="/mcp",
                log_level="INFO",
                args=[],
            ),
            environment=SimpleNamespace(build_command=lambda command: command),
            source=SimpleNamespace(load_server=fake_load_server),
        )

        monkeypatch.setattr(
            securemcp_cli.fastmcp_cli_module,
            "load_and_merge_config",
            lambda *args, **kwargs: (config, "server.py"),
        )
        monkeypatch.setattr(
            securemcp_cli, "_ORIGINAL_RUN_WITH_RELOAD", fake_run_with_reload
        )

        command, bound, _ = securemcp_cli.app.parse_args(
            ["run", "server.py", "--reload", "--no-banner"]
        )

        await command(**bound.arguments)

        assert captured["command"][0] == "securemcp"
        assert captured["command"][1:3] == ["run", "server.py"]

    async def test_securemcp_dev_inspector_uses_securemcp_spawn(self, monkeypatch):
        calls: list[list[str]] = []

        class FakeProcess:
            returncode = 0
            stdout = "9.0.0"

        def fake_subprocess_run(command: list[str], *args, **kwargs):
            calls.append(command)
            return FakeProcess()

        async def fake_load_server():
            return object()

        config = SimpleNamespace(
            deployment=SimpleNamespace(port=8123),
            environment=SimpleNamespace(
                build_command=lambda command: command,
                editable=[],
                dependencies=[],
            ),
            source=SimpleNamespace(load_server=fake_load_server),
        )

        monkeypatch.setattr(
            securemcp_cli.fastmcp_cli_module,
            "load_and_merge_config",
            lambda *args, **kwargs: (config, "server.py"),
        )
        monkeypatch.setattr(
            securemcp_cli, "_ORIGINAL_CLI_SUBPROCESS_RUN", fake_subprocess_run
        )

        command, bound, _ = securemcp_cli.app.parse_args(
            ["dev", "inspector", "server.py", "--no-reload"]
        )

        with pytest.raises(SystemExit) as exc_info:
            await command(**bound.arguments)

        assert exc_info.value.code == 0
        assert calls[-1][-4:] == ["securemcp", "run", "server.py", "--no-banner"]

    async def test_securemcp_dev_apps_launcher_uses_securemcp_module(self, monkeypatch):
        captured: dict[str, Any] = {}

        async def fake_create_subprocess_exec(*command, **kwargs):
            captured["command"] = list(command)
            captured["start_new_session"] = kwargs["start_new_session"]
            return object()

        monkeypatch.setattr(
            asyncio, "create_subprocess_exec", fake_create_subprocess_exec
        )

        await securemcp_cli._secure_start_user_server("server.py", 8100, reload=False)

        assert captured["command"][1:4] == ["-m", "securemcp", "run"]
