"""Policy monitoring and anomaly detection for SecureMCP.

Tracks policy decision metrics over time and detects anomalies
such as sudden denial rate spikes, unusual access patterns, or
policy effectiveness degradation.

Example::

    from fastmcp.server.security.policy.monitoring import PolicyMonitor

    monitor = PolicyMonitor(audit_log=audit_log, event_bus=event_bus)

    # Record decisions as they happen
    monitor.record_decision(decision="deny", resource_id="admin-panel")

    # Check for anomalies
    alerts = monitor.check_anomalies()
    for alert in alerts:
        print(f"ALERT: {alert.message} (severity: {alert.severity})")

    # Get metrics snapshot
    metrics = monitor.get_metrics()
"""

from __future__ import annotations

import logging
import threading
from collections import deque
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from enum import Enum
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from fastmcp.server.security.alerts.bus import SecurityEventBus
    from fastmcp.server.security.policy.audit import PolicyAuditLog

logger = logging.getLogger(__name__)


class AlertLevel(Enum):
    """Severity level for monitoring alerts."""

    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


@dataclass(frozen=True)
class MonitoringAlert:
    """An alert generated by the monitoring system.

    Attributes:
        level: Severity of the alert.
        message: Human-readable description.
        metric: Which metric triggered the alert.
        current_value: The current metric value.
        threshold: The threshold that was exceeded.
        timestamp: When the alert was generated.
    """

    level: AlertLevel
    message: str
    metric: str
    current_value: float
    threshold: float
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> dict[str, Any]:
        """Export as JSON-serializable dict."""
        return {
            "level": self.level.value,
            "message": self.message,
            "metric": self.metric,
            "current_value": self.current_value,
            "threshold": self.threshold,
            "timestamp": self.timestamp.isoformat(),
        }


@dataclass
class _DecisionRecord:
    """Internal record of a policy decision for time-window tracking."""

    decision: str
    resource_id: str
    actor_id: str | None
    timestamp: datetime


class PolicyMonitor:
    """Monitors policy decisions and detects anomalies.

    Tracks denial rates, per-resource patterns, and per-actor patterns
    in a sliding time window. Emits alerts when thresholds are exceeded.

    Args:
        audit_log: Optional PolicyAuditLog for historical analysis.
        event_bus: Optional event bus for emitting alerts.
        window_seconds: Sliding window for anomaly detection (default: 300s / 5min).
        deny_rate_warning: Deny rate threshold for WARNING alerts (default: 0.3 / 30%).
        deny_rate_critical: Deny rate threshold for CRITICAL alerts (default: 0.6 / 60%).
        burst_threshold: Number of denials in window for burst alert (default: 20).
        max_records: Maximum decision records to keep in memory (default: 10000).
    """

    def __init__(
        self,
        *,
        audit_log: PolicyAuditLog | None = None,
        event_bus: SecurityEventBus | None = None,
        window_seconds: int = 300,
        deny_rate_warning: float = 0.3,
        deny_rate_critical: float = 0.6,
        burst_threshold: int = 20,
        max_records: int = 10_000,
    ) -> None:
        self._audit_log = audit_log
        self._event_bus = event_bus
        self._window_seconds = window_seconds
        self._deny_rate_warning = deny_rate_warning
        self._deny_rate_critical = deny_rate_critical
        self._burst_threshold = burst_threshold
        self._records: deque[_DecisionRecord] = deque(maxlen=max_records)
        self._lock = threading.Lock()
        self._total_decisions = 0
        self._total_denials = 0
        self._alert_history: deque[MonitoringAlert] = deque(maxlen=1000)
        # Cooldown: don't emit the same alert type within this period
        self._last_alert_times: dict[str, datetime] = {}
        self._alert_cooldown = timedelta(seconds=60)

    def record_decision(
        self,
        *,
        decision: str,
        resource_id: str = "",
        actor_id: str | None = None,
    ) -> None:
        """Record a policy decision for monitoring.

        Args:
            decision: The decision string ("allow", "deny", "defer").
            resource_id: The resource that was accessed.
            actor_id: The actor who made the request.
        """
        record = _DecisionRecord(
            decision=decision.lower(),
            resource_id=resource_id,
            actor_id=actor_id,
            timestamp=datetime.now(timezone.utc),
        )
        with self._lock:
            self._records.append(record)
            self._total_decisions += 1
            if record.decision == "deny":
                self._total_denials += 1

    def check_anomalies(self) -> list[MonitoringAlert]:
        """Check current metrics against thresholds.

        Returns:
            List of new alerts (empty if everything is normal).
        """
        alerts: list[MonitoringAlert] = []
        now = datetime.now(timezone.utc)
        cutoff = now - timedelta(seconds=self._window_seconds)

        with self._lock:
            window_records = [r for r in self._records if r.timestamp >= cutoff]

        if not window_records:
            return alerts

        total = len(window_records)
        denials = sum(1 for r in window_records if r.decision == "deny")
        deny_rate = denials / total if total > 0 else 0.0

        # Check denial rate
        if deny_rate >= self._deny_rate_critical:
            alert = MonitoringAlert(
                level=AlertLevel.CRITICAL,
                message=f"Critical denial rate: {deny_rate:.1%} in last {self._window_seconds}s "
                f"({denials}/{total} requests denied)",
                metric="deny_rate",
                current_value=deny_rate,
                threshold=self._deny_rate_critical,
            )
            if self._should_emit("deny_rate_critical", now):
                alerts.append(alert)
                self._emit_alert(alert)

        elif deny_rate >= self._deny_rate_warning:
            alert = MonitoringAlert(
                level=AlertLevel.WARNING,
                message=f"Elevated denial rate: {deny_rate:.1%} in last {self._window_seconds}s "
                f"({denials}/{total} requests denied)",
                metric="deny_rate",
                current_value=deny_rate,
                threshold=self._deny_rate_warning,
            )
            if self._should_emit("deny_rate_warning", now):
                alerts.append(alert)
                self._emit_alert(alert)

        # Check burst denials
        if denials >= self._burst_threshold:
            alert = MonitoringAlert(
                level=AlertLevel.WARNING,
                message=f"Denial burst detected: {denials} denials in last {self._window_seconds}s",
                metric="deny_burst",
                current_value=float(denials),
                threshold=float(self._burst_threshold),
            )
            if self._should_emit("deny_burst", now):
                alerts.append(alert)
                self._emit_alert(alert)

        # Check per-resource concentration
        resource_denials: dict[str, int] = {}
        for r in window_records:
            if r.decision == "deny" and r.resource_id:
                resource_denials[r.resource_id] = resource_denials.get(r.resource_id, 0) + 1

        for resource_id, count in resource_denials.items():
            if count >= self._burst_threshold // 2:
                alert_key = f"resource_burst_{resource_id}"
                alert = MonitoringAlert(
                    level=AlertLevel.WARNING,
                    message=f"Resource '{resource_id}' has {count} denials in last {self._window_seconds}s",
                    metric="resource_deny_burst",
                    current_value=float(count),
                    threshold=float(self._burst_threshold // 2),
                )
                if self._should_emit(alert_key, now):
                    alerts.append(alert)
                    self._emit_alert(alert)

        return alerts

    def get_metrics(self) -> dict[str, Any]:
        """Get a snapshot of current monitoring metrics.

        Returns:
            Dict with current rates, counts, and window stats.
        """
        now = datetime.now(timezone.utc)
        cutoff = now - timedelta(seconds=self._window_seconds)

        with self._lock:
            window_records = [r for r in self._records if r.timestamp >= cutoff]
            total_decisions = self._total_decisions
            total_denials = self._total_denials

        total_window = len(window_records)
        denials_window = sum(1 for r in window_records if r.decision == "deny")
        allows_window = sum(1 for r in window_records if r.decision == "allow")
        defers_window = sum(1 for r in window_records if r.decision == "defer")
        deny_rate = denials_window / total_window if total_window > 0 else 0.0

        # Top denied resources in window
        resource_denials: dict[str, int] = {}
        for r in window_records:
            if r.decision == "deny" and r.resource_id:
                resource_denials[r.resource_id] = resource_denials.get(r.resource_id, 0) + 1
        top_denied = sorted(
            resource_denials.items(), key=lambda x: x[1], reverse=True
        )[:5]

        # Unique actors in window
        unique_actors = len(
            {r.actor_id for r in window_records if r.actor_id is not None}
        )

        return {
            "window_seconds": self._window_seconds,
            "window": {
                "total": total_window,
                "allowed": allows_window,
                "denied": denials_window,
                "deferred": defers_window,
                "deny_rate": round(deny_rate, 4),
                "unique_actors": unique_actors,
                "top_denied_resources": [
                    {"resource_id": rid, "count": c} for rid, c in top_denied
                ],
            },
            "lifetime": {
                "total_decisions": total_decisions,
                "total_denials": total_denials,
                "deny_rate": round(
                    total_denials / total_decisions if total_decisions > 0 else 0.0, 4
                ),
            },
            "thresholds": {
                "deny_rate_warning": self._deny_rate_warning,
                "deny_rate_critical": self._deny_rate_critical,
                "burst_threshold": self._burst_threshold,
            },
            "alert_count": len(self._alert_history),
            "generated_at": now.isoformat(),
        }

    def get_recent_alerts(self, limit: int = 50) -> list[dict[str, Any]]:
        """Get recent monitoring alerts.

        Args:
            limit: Maximum number of alerts to return.

        Returns:
            List of alert dicts, most recent first.
        """
        alerts = list(self._alert_history)[-limit:]
        alerts.reverse()
        return [a.to_dict() for a in alerts]

    def _should_emit(self, alert_key: str, now: datetime) -> bool:
        """Check if an alert should be emitted (cooldown check)."""
        last = self._last_alert_times.get(alert_key)
        if last is not None and (now - last) < self._alert_cooldown:
            return False
        self._last_alert_times[alert_key] = now
        return True

    def _emit_alert(self, alert: MonitoringAlert) -> None:
        """Store alert and optionally emit to event bus."""
        self._alert_history.append(alert)

        if self._event_bus is not None:
            try:
                from fastmcp.server.security.alerts.models import (
                    AlertSeverity,
                    SecurityEvent,
                    SecurityEventType,
                )

                severity_map = {
                    AlertLevel.INFO: AlertSeverity.INFO,
                    AlertLevel.WARNING: AlertSeverity.WARNING,
                    AlertLevel.CRITICAL: AlertSeverity.CRITICAL,
                }

                self._event_bus.emit(
                    SecurityEvent(
                        event_type=SecurityEventType.POLICY_DENIED,
                        severity=severity_map.get(alert.level, AlertSeverity.WARNING),
                        layer="policy-monitor",
                        message=alert.message,
                        data={
                            "metric": alert.metric,
                            "current_value": alert.current_value,
                            "threshold": alert.threshold,
                        },
                    )
                )
            except Exception:
                logger.debug("Failed to emit monitoring alert to event bus", exc_info=True)
